name: styler
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Add the Cupertino Icons font for iOS style icons.
  cupertino_icons: ^1.0.6
  
  # Splash screen support
  flutter_native_splash: ^2.4.1
  
  # Google Fonts package for custom fonts
  google_fonts: ^6.2.1
  
  # Image Picker package for selecting images
  image_picker: ^1.1.2
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  go_router: ^14.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Recommended lints for Flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#FFFFFF"  # Corrected background color format (hex with quotes)
  image: assets/images/splash.png  # Path to your splash image
  android: true  # Enable splash for Android
  ios: true  # Enable splash for iOS
  web: false  # Set to true if you're building for web

flutter:

  # Ensures that Material Icons font is included with your application
  uses-material-design: true

  # Add assets to your application
  assets:
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/images/image5.png
    - assets/images/image6.png
    - assets/images/image7.png
    - assets/images/image8.png
    - assets/images/tailor.png
    - assets/images/splash.png
    - assets/images/forgot_password.png
    - assets/images/most_popular.png
    - assets/images/specialOffer/offer1.png
    - assets/images/specialOffer/offer2.png
    - assets/images/specialOffer/offer3.png
    - assets/images/specialOffer/offer4.png
    - assets/images/specialOffer/offer5.png
    

  # Add custom fonts
  # Uncomment and add font details if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
